version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

  db:
    image: "postgres:alpine"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    #      - ./sql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge