# Generated by Django 4.2.7 on 2023-11-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_alter_currency_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['id'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
